# Generated by Django 4.2.6 on 2023-11-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Heading')),
                ('textContent', models.TextField(verbose_name='Text')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('date', models.DateField(verbose_name='Date of publication')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
    ]
