# Generated by Django 4.2.6 on 2023-11-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='image/%Y', verbose_name='Images'),
            preserve_default=False,
        ),
    ]
